[package]
name = "mehubot"
version = "0.1.0"
authors = ["Andreas Metsälä <andreas.metsala@gmail.com>"]

[dependencies]
dotenv = "0.10.1"
reqwest = "0.8.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.5"
rusqlite = "0.13"